<a href="https://colab.research.google.com/github/asegura4488/MetodosComputacionales2026/blob/main/Semana12/RetornoInversion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
# Vamos a cargar datos
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [6]:
import os
os.chdir("/content/drive/MyDrive/ColabNotebooks/Cursos/MetodosComputacionales2026")

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.optimize import minimize
import itertools

Data = pd.read_csv('Semana12/Data/cuotas.csv')
Data

   Local  Empate  Visitante
0   2.17     3.1       3.75
1   1.71     3.7       5.10

In [11]:
opciones = list(Data.columns)
opciones

['Local', 'Empate', 'Visitante']

In [13]:
# Combinaciones
combinaciones = list(itertools.product(opciones, repeat = len(Data)))
combinaciones

[('Local', 'Local'),
 ('Local', 'Empate'),
 ('Local', 'Visitante'),
 ('Empate', 'Local'),
 ('Empate', 'Empate'),
 ('Empate', 'Visitante'),
 ('Visitante', 'Local'),
 ('Visitante', 'Empate'),
 ('Visitante', 'Visitante')]

In [20]:
registros = []

for combo in combinaciones:

  couta_total = 1.0

  for  i, eleccion in enumerate(combo):
    #print(i,eleccion)
    couta_total *= Data.iloc[i][eleccion]
    #print(couta_total)

    etiqueta = '_'.join(combo)

  registros.append({
      "Combinacion": etiqueta,
      "CuotaTotal": couta_total
      })

df_comb = pd.DataFrame(registros)
df_comb

           Combinacion  CuotaTotal
0          Local_Local      3.7107
1         Local_Empate      8.0290
2      Local_Visitante     11.0670
3         Empate_Local      5.3010
4        Empate_Empate     11.4700
5     Empate_Visitante     15.8100
6      Visitante_Local      6.4125
7     Visitante_Empate     13.8750
8  Visitante_Visitante     19.1250

In [21]:
# Definimos la metrica a maximizar
def fun_objetivo(w,ganancias,Capital):
  return  w * ganancias * Capital - Capital