<a href="https://colab.research.google.com/github/asegura4488/MetodosComputacionales2026/blob/main/Semana13/RiesgoMaterias.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Vamos a cargar datos
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [2]:
import os
os.chdir("/content/drive/MyDrive/ColabNotebooks/Cursos/MetodosComputacionales2026")

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.optimize import minimize
import itertools

df = pd.read_csv('Semana13/Data/datos_materias_riesgo.csv')
df

,Materia,Parcial_1,Parcial_2,Hora_clase,Horas_estudio_semana,Dificultad_profesor_1a5
0,Calculo,2.4,2.8,07:00,5,4
1,Algebra Lineal,3.0,2.9,10:00,4,3
2,Fisica Moderna,2.1,2.5,16:00,7,5

In [4]:
# Umbral
nota_aprobacion = 3.0
peso_p1 = 0.30
peso_p2 = 0.30
peso_faltante = 0.40

In [8]:
df['Nota_acumuladta'] = peso_p1 * df['Parcial_1'] + peso_p2 * df['Parcial_2']
df['Nota_necesaria'] = (nota_aprobacion-df['Nota_acumuladta']) / peso_faltante
df

,Materia,Parcial_1,Parcial_2,Hora_clase,Horas_estudio_semana,Dificultad_profesor_1a5,Nota_acumuladta,Nota_necesaria
0,Calculo,2.4,2.8,07:00,5,4,1.56,3.600
1,Algebra Lineal,3.0,2.9,10:00,4,3,1.77,3.075
2,Fisica Moderna,2.1,2.5,16:00,7,5,1.38,4.050

In [12]:
df['R_nota'] = df['Nota_necesaria'] / 5
# riesgo por el profesor
df['R_profesor'] = df['Dificultad_profesor_1a5'] / 5
# riesgo por horas
df['R_tiempo'] = df['Horas_estudio_semana'] / df['Horas_estudio_semana'].max()
df

,Materia,Parcial_1,Parcial_2,Hora_clase,Horas_estudio_semana,Dificultad_profesor_1a5,Nota_acumuladta,Nota_necesaria,R_nota,R_profesor,R_tiempo
0,Calculo,2.4,2.8,07:00,5,4,1.56,3.600,0.720,0.8,0.714286
1,Algebra Lineal,3.0,2.9,10:00,4,3,1.77,3.075,0.615,0.6,0.571429
2,Fisica Moderna,2.1,2.5,16:00,7,5,1.38,4.050,0.810,1.0,1.000000

In [17]:
def riesgo_horario(hora):

  h = int(hora.split(':')[0])
  print(h)
  if h <= 7:
    return 0.7
  elif 10 <= h <= 14:
    return 0.2
  elif h >= 18:
    return 0.6
  else:
    return 0.4

In [18]:
df['R_horario'] = df['Hora_clase'].apply(riesgo_horario)
df

7
10
16

,Materia,Parcial_1,Parcial_2,Hora_clase,Horas_estudio_semana,Dificultad_profesor_1a5,Nota_acumuladta,Nota_necesaria,R_nota,R_profesor,R_tiempo,R_horario
0,Calculo,2.4,2.8,07:00,5,4,1.56,3.600,0.720,0.8,0.714286,0.7
1,Algebra Lineal,3.0,2.9,10:00,4,3,1.77,3.075,0.615,0.6,0.571429,0.2
2,Fisica Moderna,2.1,2.5,16:00,7,5,1.38,4.050,0.810,1.0,1.000000,0.4